### ISSUE TITLE
Error on round end while wearing hat

### ISSUE THREAD

**Issue by EsserGaming** [RowpannSCP/Hats#1]
After the round ends, while wearing a hat, the plugin throws an error:
https://pastebin.com/vdaiiS0M

**Comment by EsserGaming** [comment]
To add onto this issue: The plugin doesn't keep the hat loaded when the round restarts, so you'll have to remove and then re-add the hat in order for it to be on you again.

**Comment by EsserGaming** [comment]
And also to add on to this issue, offsets don't seem to work, even after a server restart.

**Comment by moddedmcplayer** [comment]
Round restart is not really a bug since thats when the hats are loaded, I can try to only load them once and reload via command

**Comment by moddedmcplayer** [comment]
Ill try to fix it
